"""Protocol-agnostic core foundation for litestar-mcp.

This package hosts stateless JSON-RPC 2.0 dispatching, JSON Schema Draft 2020-12
reflection, handler parameter introspection, generic SSE stream queueing,
and cursor pagination encoding.
"""

from litestar_mcp.core._cursor import decode_cursor, encode_cursor
from litestar_mcp.core.jsonrpc import (
    INTERNAL_ERROR,
    INVALID_PARAMS,
    INVALID_REQUEST,
    METHOD_NOT_FOUND,
    PARSE_ERROR,
    JSONRPCError,
    JSONRPCErrorException,
    JSONRPCRequest,
    JSONRPCRouter,
    MethodHandler,
    error_response,
    parse_request,
)
from litestar_mcp.core.schema import (
    attrs_to_json_schema,
    basic_type_to_json_schema,
    collection_type_to_json_schema,
    dataclass_to_json_schema,
    generate_schema_for_handler,
    model_to_json_schema,
    msgspec_to_json_schema,
    pydantic_to_json_schema,
    type_to_json_schema,
    union_type_to_json_schema,
)
from litestar_mcp.core.serialization import (
    SchemaSerializer,
    get_collection_serializer,
    reset_serializer_cache,
    schema_dump,
    serialize_collection,
)
from litestar_mcp.core.signature import (
    AdvertisedHandlerParameter,
    extract_advertised_handler_arguments,
    get_advertised_handler_parameters,
    get_handler_function,
    iter_dependency_input_parameters,
    parameter_aliases,
    resolve_tool_argument_aliases,
)
from litestar_mcp.core.sse import (
    BaseSubscriptionManager,
    StreamLimitExceeded,
    StreamSubscription,
)
from litestar_mcp.core.typing import (
    ATTRS_INSTALLED,
    DISHKA_INSTALLED,
    MSGSPEC_INSTALLED,
    PYDANTIC_INSTALLED,
    AttrsInstance,
    BaseModel,
    DataclassProtocol,
    DictLike,
    DishkaDependencyKey,
    Struct,
    SupportedSchemaModel,
    is_attrs_instance,
    is_attrs_schema,
    is_dataclass,
    is_dict,
    is_msgspec_struct,
    is_pydantic_model,
    is_schema_model,
)

__all__ = (
    "ATTRS_INSTALLED",
    "DISHKA_INSTALLED",
    "INTERNAL_ERROR",
    "INVALID_PARAMS",
    "INVALID_REQUEST",
    "METHOD_NOT_FOUND",
    "MSGSPEC_INSTALLED",
    "PARSE_ERROR",
    "PYDANTIC_INSTALLED",
    "AdvertisedHandlerParameter",
    "AttrsInstance",
    "BaseModel",
    "BaseSubscriptionManager",
    "DataclassProtocol",
    "DictLike",
    "DishkaDependencyKey",
    "JSONRPCError",
    "JSONRPCErrorException",
    "JSONRPCRequest",
    "JSONRPCRouter",
    "MethodHandler",
    "SchemaSerializer",
    "StreamLimitExceeded",
    "StreamSubscription",
    "Struct",
    "SupportedSchemaModel",
    "attrs_to_json_schema",
    "basic_type_to_json_schema",
    "collection_type_to_json_schema",
    "dataclass_to_json_schema",
    "decode_cursor",
    "encode_cursor",
    "error_response",
    "extract_advertised_handler_arguments",
    "generate_schema_for_handler",
    "get_advertised_handler_parameters",
    "get_collection_serializer",
    "get_handler_function",
    "is_attrs_instance",
    "is_attrs_schema",
    "is_dataclass",
    "is_dict",
    "is_msgspec_struct",
    "is_pydantic_model",
    "is_schema_model",
    "iter_dependency_input_parameters",
    "model_to_json_schema",
    "msgspec_to_json_schema",
    "parameter_aliases",
    "parse_request",
    "pydantic_to_json_schema",
    "reset_serializer_cache",
    "resolve_tool_argument_aliases",
    "schema_dump",
    "serialize_collection",
    "type_to_json_schema",
    "union_type_to_json_schema",
)
